dbt_nexstay:
  target: postgres
  outputs:
    postgres:
      type: postgres
      threads: 4
      host: "{{ env_var('DBT_PG_HOST', 'db') }}"
      port: "{{ env_var('DBT_PG_PORT', 5432) | int }}"
      user: "{{ env_var('DBT_PG_USER', 'nextstay') }}"
      pass: "{{ env_var('DBT_PG_PASS', 'nextstay') }}"
      dbname: "{{ env_var('DBT_PG_DBNAME', 'nextstay') }}"
      schema: stg
    duckdb:
      type: duckdb
      path: "{{ env_var('DBT_DUCKDB_PATH', '/opt/airflow/dbt/dev.duckdb') }}"
      threads: 4
