-- Room detail fields and extended task metadata

ALTER TABLE rooms ADD COLUMN IF NOT EXISTS photo_url VARCHAR(500);
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS area_sqm INTEGER;
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS bed_type VARCHAR(50);
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS view_type VARCHAR(50);
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS floor INTEGER;

ALTER TABLE cleaning_tasks ADD COLUMN IF NOT EXISTS task_type VARCHAR(30) NOT NULL DEFAULT 'cleaning';
ALTER TABLE cleaning_tasks ADD COLUMN IF NOT EXISTS due_at TIMESTAMPTZ;
