dbt_nexstay:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: nextstay_db_clean
      port: 5432
      user: admin
      pass: nextstay_secure_pass
      dbname: nextstay_db_v2
      schema: stg
  target: dev
