import { useNavigate } from "react-router-dom";
import Card from "../../ui/Card";
import PageHeader from "../../ui/PageHeader";
import { useAuthStore, canManageEngine } from "../../store/authStore";

const sections = [
  {
    path: "/inventory-setup",
    title: "Inventory Setup",
    description:
      "Define your room types, count, prices and capacity. Apply them to the site and generate a synthetic training dataset in one click.",
    step: "1",
    color: "blue",
  },
  {
    path: "/model-training",
    title: "Model Training",
    description:
      "Upload a training CSV, trigger per-hotel model training, monitor job progress, and promote the best model to production.",
    step: "2",
    color: "violet",
  },
  {
    path: "/pricing-lab",
    title: "Pricing Lab",
    description:
      "Inspect live dynamic prices generated by the engine. Run a pricing snapshot to reprice all room types for the next 30 days.",
    step: "3",
    color: "emerald",
  },
  {
    path: "/engine-tuning",
    title: "Engine Tuning",
    description:
      "Set per-hotel business rules: price floors and ceilings, weekend and holiday multipliers, and rollout fraction.",
    step: "4",
    color: "amber",
  },
];

const colorMap: Record<string, string> = {
  blue:   "border-blue-200 dark:border-blue-800 hover:border-blue-400 dark:hover:border-blue-600",
  violet: "border-violet-200 dark:border-violet-800 hover:border-violet-400 dark:hover:border-violet-600",
  emerald:"border-emerald-200 dark:border-emerald-800 hover:border-emerald-400 dark:hover:border-emerald-600",
  amber:  "border-amber-200 dark:border-amber-800 hover:border-amber-400 dark:hover:border-amber-600",
};

const badgeMap: Record<string, string> = {
  blue:   "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300",
  violet: "bg-violet-100 text-violet-700 dark:bg-violet-900/40 dark:text-violet-300",
  emerald:"bg-emerald-100 text-emerald-700 dark:bg-emerald-900/40 dark:text-emerald-300",
  amber:  "bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300",
};

export default function EngineHubPage() {
  const navigate  = useNavigate();
  const role      = useAuthStore((s) => s.role);
  const canManage = canManageEngine(role);

  const visibleSections = canManage
    ? sections
    : sections.filter((s) => s.path === "/inventory-setup" || s.path === "/pricing-lab");

  return (
    <div className="w-full space-y-6">
      <PageHeader
        title="Pricing Engine"
        subtitle="Dynamic pricing tools for your hotel."
      />

      <div className="grid gap-4 md:grid-cols-2">
        {visibleSections.map((s) => (
          <button
            key={s.path}
            onClick={() => navigate(s.path)}
            className={`text-left w-full rounded-xl border-2 bg-white dark:bg-gray-900 p-5 transition-all cursor-pointer shadow-sm hover:shadow-md ${colorMap[s.color]}`}
          >
            <div className="flex items-start gap-4">
              <span className={`mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-sm font-bold ${badgeMap[s.color]}`}>
                {s.step}
              </span>
              <div>
                <h3 className="font-semibold text-gray-900 dark:text-white text-sm mb-1">{s.title}</h3>
                <p className="text-xs text-gray-500 dark:text-gray-400 leading-relaxed">{s.description}</p>
              </div>
            </div>
          </button>
        ))}
      </div>

      <Card padding="md">
        <h2 className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-3">
          {canManage ? "Full pipeline in 4 steps" : "Available tools"}
        </h2>
        <ol className="space-y-2 text-sm text-gray-600 dark:text-gray-400 list-decimal list-inside">
          <li><strong>Inventory Setup</strong> — define room types, apply to site, download training CSV</li>
          {canManage && <li><strong>Model Training</strong> — upload CSV, train per-hotel model, promote it</li>}
          <li><strong>Pricing Lab</strong> — inspect dynamic prices</li>
          {canManage && <li><strong>Engine Tuning</strong> — adjust price bounds, multipliers and rollout rules anytime</li>}
        </ol>
      </Card>
    </div>
  );
}
